import numpy as np
import cv2

# Set the defaults for hog features
DEFAULT_CSPACE='YCrCb'
DEFAULT_ORIENT=9
DEFAULT_PIX_PER_CELL=8
DEFAULT_CELL_PER_BLOCK=2
DEFAULT_HOG_CHANNEL='ALL' # 0, 1, 2, or 'ALL'

## Set Default parameters for color feature extraction
DEFAULT_SPATIAL_SIZEX=32
DEFAULT_SPATIAL_SIZEY=32
DEFAULT_SPATIAL_SIZE=(DEFAULT_SPATIAL_SIZEX, DEFAULT_SPATIAL_SIZEY)
DEFAULT_HIST_BIN=32
DEFAULT_HIST_RANGE=(0,256)

USE_SPATIAL_FEAT=True
USE_HIST_FEAT=True
USE_HOG_FEAT=True

NATIVE_COLOR_SPACE='BGR'

